### ISSUE TITLE
Unable to create / Edit Email List

### ISSUE THREAD

**Issue by AyushAllBlue** [SubscribeIT/ngDesk#88] opened 2021-08-26 07:10 UTC
**Owner:** @ssatish 

**Task Type:** 
- [ ] New 
- [ ] Improvemnt 
- [x] Bug

**Projects Affected (Ex. UI, Data-Service):** 

**Components/Services Affected (Ex. Login Component, POST Data API):**

**General Description/Overview:**

We observed that user is unable to create/ Edit email list following error is displayed on creating an email list with valid conditions.

Internal server error. Please try again or contact support.

**List of Steps:**

1. Navigate to dev1.ngdesk.com with valid admin credentials.
2. Click on the 'Company Settings' sidebar menu --> Email List --> New button.
3. click on the add conditions icon.
4. select conditions as 'Role' , operator as 'equals to' and value as 'Customer'.
5. click on the save button.

**Screenshot**

![30](https://user-images.githubusercontent.com/89504119/130954008-40738484-7c3c-4b5a-abc5-1453ab8bf17d.png)

**Test Criteria:**

**Comment by sdthengil** [comment] 2021-09-06 10:18
Issue is not replicating.Perform below steps while testing.

1.Clicked on the 'Company Settings' sidebar menu --> Email List --> New button.
2.clicked on the add conditions icon.
3.select conditions as 'Role' , operator as 'equals to' and value as 'Customer'.
4.able to save the email list.
5.also observed no error while editing the email list.

issue is fixed.

/spend 1h

**Comment by karthikbalu1** [comment] 2021-09-06 10:21
The issue is fixed already so closing the issue.

**Closed by karthikbalu1** 2021-09-06 10:21 UTC
Labels: bug
